# примеры API-запросов

#@baseUrl = https://localhost:8000/api/v1

# 9687c6d41a402d6ae65ba18137aca5e0e061eae7   admin
# 2e7f4d2dc285a5102a818044b78081d81071a316   denis

# получение объявлений
GET http://localhost:8000/api/v1/advertisements/
Content-Type: application/json

###

# создание объявления
POST http://localhost:8000/api/v1/advertisements/
Content-Type: application/json
Authorization: Token 2e7f4d2dc285a5102a818044b78081d81071a316

{
  "title": "Шкаф 111",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://localhost:8000/api/v1/advertisements/8/
Content-Type: application/json
Authorization: Token 2e7f4d2dc285a5102a818044b78081d81071a316

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://localhost:8000/api/v1/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET http://localhost:8000/api/v1/advertisements/?created_at_before=2021-09-01
Content-Type: application/json

###
GET http://localhost:8000/api/v1/advertisements/?status=CLOSED
Content-Type: application/json